name: Build & Test contracts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.cargo
            **/target
          key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-rust-

      - name: Install Rust
        run: npx xsuite install-rust --toolchain none && rustc --version

      - name: Build all contracts
        run: npm run build

      - name: Test all contracts
        run: npm run test
